version: '3.8'

services:
  video-api-dev:
    build:
      context: .
      target: development
    volumes:
      - ./:/vid-splitter/server/
      - /vid-splitter/server/node_modules
    ports:
      - 6969:6969
    command: npm run dev
